name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
# psg/black@stable is broken ATM, use master in the meantime: https://github.com/psf/black/issues/1520
#      - uses: psf/black@stable
      - uses: psf/black@master
